name: "Deploy to Server"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build using MkDocs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jnanadarshan/mkdocs-build-action@v1
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1

  upload:
    name: "Upload to server"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "."
          target: "~/docs"
